-- =========================================================================
-- 1. CLEANUP ALL EXISTING STRUCTURES (SAFE FOR FRESH & RESETS)
-- =========================================================================
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.tasks CASCADE;
DROP TABLE IF EXISTS public.board_members CASCADE;
DROP TABLE IF EXISTS public.boards CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

DROP FUNCTION IF EXISTS public.create_notification(uuid, text, text, text, uuid) CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.handle_task_changes() CASCADE;
DROP FUNCTION IF EXISTS public.notify_board_member_changes() CASCADE;
DROP FUNCTION IF EXISTS public.send_task_due_reminder_for_task(uuid) CASCADE;
DROP FUNCTION IF EXISTS public.send_task_due_reminder_notification() CASCADE;
DROP FUNCTION IF EXISTS public.set_created_by() CASCADE;

-- =========================================================================
-- 2. CREATE CORE TABLES
-- =========================================================================

-- PROFILES (Linked to Supabase Auth Users)
CREATE TABLE public.profiles (
    id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email text,
    full_name text,
    avatar_url text,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- PROJECTS
CREATE TABLE public.projects (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    description text,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- BOARDS
CREATE TABLE public.boards (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    project_id uuid REFERENCES public.projects(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- BOARD MEMBERS
CREATE TABLE public.board_members (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    board_id uuid REFERENCES public.boards(id) ON DELETE CASCADE,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    role text DEFAULT 'Member'::text NOT NULL,
    status text DEFAULT 'Invited'::text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(board_id, user_id)
);

-- TASKS (Uses a standard single UUID to perfectly match your frontend task payload)
CREATE TABLE public.tasks (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    board_id uuid REFERENCES public.boards(id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL,
    description text,
    status text DEFAULT 'todo'::text NOT NULL,
    due_date timestamp with time zone,
    assigned_to uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- NOTIFICATIONS (Uses bigint sequence identity matching your exact frontend order rules)
CREATE TABLE public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    type text NOT NULL,
    related_id uuid,
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- 3. CREATE ALL 7 DATABASE FUNCTIONS
-- =========================================================================

-- FUNCTION 1: create_notification
CREATE OR REPLACE FUNCTION public.create_notification(
    p_user_id uuid,
    p_title text,
    p_message text,
    p_type text,
    p_related_id uuid DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO public.notifications (user_id, title, message, type, related_id)
    VALUES (p_user_id, p_title, p_message, p_type, p_related_id);
END;
$$;

-- FUNCTION 2: handle_new_user
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger 
SECURITY DEFINER SET search_path = public
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$;

-- FUNCTION 3: handle_task_changes
CREATE OR REPLACE FUNCTION public.handle_task_changes()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_board_name text;
BEGIN
  -- Insert Event Handler
  IF TG_OP = 'INSERT' THEN
    IF NEW.assigned_to IS NOT NULL AND NEW.status <> 'done' THEN
      IF NEW.assigned_to IS DISTINCT FROM NEW.created_by AND EXISTS (SELECT 1 FROM public.profiles WHERE id = NEW.assigned_to) THEN
        PERFORM public.create_notification(NEW.assigned_to, 'Task assigned', format('You were assigned "%s".', NEW.name), 'task_assigned', NEW.id);
      END IF;
    END IF;
    
    IF NEW.due_date IS NOT NULL THEN
      PERFORM public.send_task_due_reminder_for_task(NEW.id);
    END IF;
    RETURN NEW;
  END IF;

  -- Update Event Handler
  IF TG_OP = 'UPDATE' THEN
    IF NEW.assigned_to IS NOT NULL AND NEW.status <> 'done' THEN
      IF OLD.assigned_to IS NULL OR NEW.assigned_to IS DISTINCT FROM OLD.assigned_to THEN
        IF NEW.assigned_to IS DISTINCT FROM NEW.created_by AND EXISTS (SELECT 1 FROM public.profiles WHERE id = NEW.assigned_to) THEN
          PERFORM public.create_notification(NEW.assigned_to, 'Task assigned', format('You were assigned "%s".', NEW.name), 'task_assigned', NEW.id);
        END IF;
      END IF;
    END IF;

    -- Done Status Handler
    IF NEW.status = 'done' AND OLD.status <> 'done' THEN
      SELECT name INTO v_board_name FROM public.boards WHERE id = NEW.board_id;
      IF NEW.created_by IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles WHERE id = NEW.created_by) THEN
        PERFORM public.create_notification(NEW.created_by, 'Task completed', format('Task "%s" in "%s" was completed.', NEW.name, COALESCE(v_board_name, 'the board')), 'task_completed', NEW.id);
      END IF;
      IF NEW.assigned_to IS NOT NULL AND NEW.assigned_to IS DISTINCT FROM NEW.created_by AND EXISTS (SELECT 1 FROM public.profiles WHERE id = NEW.assigned_to) THEN
        PERFORM public.create_notification(NEW.assigned_to, 'Task completed', format('Task "%s" in "%s" was completed.', NEW.name, COALESCE(v_board_name, 'the board')), 'task_completed', NEW.id);
      END IF;
    END IF;

    IF NEW.due_date IS DISTINCT FROM OLD.due_date AND NEW.due_date IS NOT NULL AND NEW.status <> 'done' THEN
      PERFORM public.send_task_due_reminder_for_task(NEW.id);
    END IF;

    RETURN NEW;
  END IF;
  RETURN NULL;
END;
$$;

-- FUNCTION 4: notify_board_member_changes
CREATE OR REPLACE FUNCTION public.notify_board_member_changes()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_board_name text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    SELECT name INTO v_board_name FROM public.boards WHERE id = NEW.board_id;
    PERFORM public.create_notification(
      NEW.user_id,
      'Board Invitation',
      format('You have been invited to join the board "%s".', COALESCE(v_board_name, 'a board')),
      'board_invite',
      NEW.board_id
    );
  END IF;
  RETURN NEW;
END;
$$;

-- FUNCTION 5: send_task_due_reminder_for_task
CREATE OR REPLACE FUNCTION public.send_task_due_reminder_for_task(p_task_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_task_name text;
  v_assigned_to uuid;
  v_due_date timestamp with time zone;
BEGIN
  SELECT name, assigned_to, due_date INTO v_task_name, v_assigned_to, v_due_date
  FROM public.tasks WHERE id = p_task_id;
  
  IF v_assigned_to IS NOT NULL AND v_due_date IS NOT NULL AND v_due_date > now() THEN
    DELETE FROM public.notifications WHERE user_id = v_assigned_to AND related_id = p_task_id AND type = 'task_due';
    PERFORM public.create_notification(
      v_assigned_to,
      'Task Reminder',
      format('Reminder: Your assigned task "%s" is due soon.', v_task_name),
      'task_due',
      p_task_id
    );
  END IF;
END;
$$;

-- FUNCTION 6: send_task_due_reminder_notification
CREATE OR REPLACE FUNCTION public.send_task_due_reminder_notification()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM public.send_task_due_reminder_for_task(id)
  FROM public.tasks
  WHERE status <> 'done' AND due_date IS NOT NULL AND due_date BETWEEN now() AND (now() + interval '1 day');
END;
$$;

-- FUNCTION 7: set_created_by
CREATE OR REPLACE FUNCTION public.set_created_by()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF NEW.created_by IS NULL THEN
    NEW.created_by := auth.uid();
  END IF;
  RETURN NEW;
END;
$$;

-- =========================================================================
-- 4. BIND TRIGGERS TO TABLES
-- =========================================================================
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER on_task_changes
  AFTER INSERT OR UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.handle_task_changes();

CREATE TRIGGER on_board_member_changes
  AFTER INSERT ON public.board_members
  FOR EACH ROW EXECUTE FUNCTION public.notify_board_member_changes();

CREATE TRIGGER set_tasks_created_by
  BEFORE INSERT ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

CREATE TRIGGER set_boards_created_by
  BEFORE INSERT ON public.boards
  FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

CREATE TRIGGER set_projects_created_by
  BEFORE INSERT ON public.projects
  FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

-- =========================================================================
-- 5. DISABLE ROW LEVEL SECURITY (UNRESTRICTED - DEVELOPMENT SETTING)
-- =========================================================================
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.boards DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;

-- =========================================================================
-- 6. INITIAL SYNC FOR ACTIVE USERS
-- =========================================================================
INSERT INTO public.profiles (id, email, full_name)
SELECT id, email, COALESCE(raw_user_meta_data->>'full_name', raw_user_meta_data->>'name', split_part(email, '@', 1))
FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- =========================================================================
-- 7. ENABLE REALTIME STREAMING PUBLICATION CHANNEL WITH FULL HISTORIES
-- =========================================================================
ALTER TABLE public.notifications REPLICA IDENTITY FULL;
ALTER TABLE public.tasks REPLICA IDENTITY FULL;

DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.tasks;