-- =========================================================================
-- 1. CLEANUP ALL EXISTING STRUCTURES (SAFE FOR FRESH RUNS & RESETS)
-- =========================================================================
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.tasks CASCADE;
DROP TABLE IF EXISTS public.board_members CASCADE;
DROP TABLE IF EXISTS public.boards CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- Drop all variants of functions to prevent signature collisions (Fixes 42725)
DROP FUNCTION IF EXISTS public.create_notification(uuid, text, text, text, uuid) CASCADE;
DROP FUNCTION IF EXISTS public.create_notification(uuid, text, text, text, uuid, jsonb) CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.handle_task_changes() CASCADE;
DROP FUNCTION IF EXISTS public.notify_board_member_changes() CASCADE;
DROP FUNCTION IF EXISTS public.send_task_due_reminder_for_task(uuid) CASCADE;
DROP FUNCTION IF EXISTS public.send_task_due_reminder_notification() CASCADE;
DROP FUNCTION IF EXISTS public.set_created_by() CASCADE;
DROP FUNCTION IF EXISTS public.has_board_access(uuid) CASCADE;
DROP FUNCTION IF EXISTS public.get_board_role(uuid) CASCADE;

-- =========================================================================
-- 2. CREATE CORE TABLES
-- =========================================================================

-- PROFILES (Linked to Supabase Auth Users)
CREATE TABLE public.profiles (
    id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email text,
    full_name text,
    avatar_url text,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- PROJECTS
CREATE TABLE public.projects (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name text NOT NULL,
    description text,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- BOARDS
CREATE TABLE public.boards (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    project_id uuid REFERENCES public.projects(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- BOARD MEMBERS
CREATE TABLE public.board_members (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    board_id uuid REFERENCES public.boards(id) ON DELETE CASCADE,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    role text DEFAULT 'Member'::text NOT NULL,
    status text DEFAULT 'Invited'::text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(board_id, user_id)
);

-- TASKS
CREATE TABLE public.tasks (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    board_id uuid REFERENCES public.boards(id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL,
    description text,
    status text DEFAULT 'todo'::text NOT NULL,
    due_date timestamp with time zone,
    assigned_to uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- NOTIFICATIONS
CREATE TABLE public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    message text NOT NULL,
    type text NOT NULL,
    related_id uuid,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- 3. HELPER FUNCTIONS & DATABASE TRIGGERS
-- =========================================================================

-- HELPER: Check if a user has access to a board (SECURITY DEFINER breaks RLS loops)
CREATE OR REPLACE FUNCTION public.has_board_access(p_board_id uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.boards WHERE id = p_board_id AND created_by = auth.uid()
  ) OR EXISTS (
    SELECT 1 FROM public.board_members WHERE board_id = p_board_id AND user_id = auth.uid() AND status IN ('Accepted', 'Pending')
  );
$$;

-- HELPER: Get a user's role in a board
CREATE OR REPLACE FUNCTION public.get_board_role(p_board_id uuid)
RETURNS text
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM public.board_members 
  WHERE board_id = p_board_id AND user_id = auth.uid() AND status = 'Accepted' 
  LIMIT 1;
$$;

-- SINGLE UNIFIED NOTIFICATION FUNCTION (Prevents 42725 errors)
CREATE OR REPLACE FUNCTION public.create_notification(
    p_user_id uuid,
    p_title text,
    p_message text,
    p_type text,
    p_related_id uuid DEFAULT NULL,
    p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.notifications (user_id, title, message, type, related_id, metadata)
  VALUES (p_user_id, p_title, p_message, p_type, p_related_id, p_metadata);
END;
$$;

-- HANDLE NEW SIGNUPS
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger 
SECURITY DEFINER SET search_path = public
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$;

-- TASK AUTOMATIONS & NOTIFICATIONS
CREATE OR REPLACE FUNCTION public.handle_task_changes()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_board_name text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.assigned_to IS NOT NULL AND NEW.status <> 'done' THEN
      IF NEW.assigned_to IS DISTINCT FROM NEW.created_by AND EXISTS (SELECT 1 FROM public.profiles WHERE id = NEW.assigned_to) THEN
        PERFORM public.create_notification(NEW.assigned_to, 'Task assigned', format('You were assigned "%s".', NEW.name), 'task_assigned', NEW.id);
      END IF;
    END IF;
    
    IF NEW.due_date IS NOT NULL THEN
      PERFORM public.send_task_due_reminder_for_task(NEW.id);
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF NEW.assigned_to IS NOT NULL AND NEW.status <> 'done' THEN
      IF OLD.assigned_to IS NULL OR NEW.assigned_to IS DISTINCT FROM OLD.assigned_to THEN
        IF NEW.assigned_to IS DISTINCT FROM NEW.created_by AND EXISTS (SELECT 1 FROM public.profiles WHERE id = NEW.assigned_to) THEN
          PERFORM public.create_notification(NEW.assigned_to, 'Task assigned', format('You were assigned "%s".', NEW.name), 'task_assigned', NEW.id);
        END IF;
      END IF;
    END IF;

    IF NEW.status = 'done' AND OLD.status <> 'done' THEN
      SELECT name INTO v_board_name FROM public.boards WHERE id = NEW.board_id;
      IF NEW.created_by IS NOT NULL AND EXISTS (SELECT 1 FROM public.profiles WHERE id = NEW.created_by) THEN
        PERFORM public.create_notification(NEW.created_by, 'Task completed', format('Task "%s" in "%s" was completed.', NEW.name, COALESCE(v_board_name, 'the board')), 'task_completed', NEW.id);
      END IF;
    END IF;

    RETURN NEW;
  END IF;
  RETURN NULL;
END;
$$;

-- BOARD MEMBER INVITATION NOTIFICATIONS (FIXED TO PREVENT OWNER SELF-SPAM)
CREATE OR REPLACE FUNCTION public.notify_board_member_changes()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_board_name text;
  v_owner_id uuid;
  v_requester_name text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    SELECT name, created_by INTO v_board_name, v_owner_id FROM public.boards WHERE id = NEW.board_id;

    -- PREVENT NOTIFICATIONS IF OWNER IS ADDING THEMSELVES
    IF v_owner_id = NEW.user_id THEN
      RETURN NEW;
    END IF;

    -- Check WHO is making the request
    IF auth.uid() = NEW.user_id THEN
      -- SCENARIO A: A user requested access.
      SELECT full_name INTO v_requester_name FROM public.profiles WHERE id = NEW.user_id;
      
      IF v_owner_id IS NOT NULL THEN
        PERFORM public.create_notification(
          v_owner_id,
          'Board Access Request',
          format('%s has requested access to the board "%s".', COALESCE(v_requester_name, 'Someone'), COALESCE(v_board_name, 'a board')),
          'access_request',
          NEW.board_id
        );
      END IF;
      
    ELSE
      -- SCENARIO B: The Owner invited the user.
      IF v_owner_id IS NOT NULL AND v_owner_id IS DISTINCT FROM NEW.user_id THEN
        PERFORM public.create_notification(
          NEW.user_id,
          'Board Invitation',
          format('You have been invited to join the board "%s".', COALESCE(v_board_name, 'a board')),
          'board_invite',
          NEW.board_id
        );
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

-- TASK DUE REMINDERS
CREATE OR REPLACE FUNCTION public.send_task_due_reminder_for_task(p_task_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_task_name text;
  v_assigned_to uuid;
  v_due_date timestamp with time zone;
BEGIN
  SELECT name, assigned_to, due_date INTO v_task_name, v_assigned_to, v_due_date
  FROM public.tasks WHERE id = p_task_id;
  
  IF v_assigned_to IS NOT NULL AND v_due_date IS NOT NULL AND v_due_date > now() THEN
    DELETE FROM public.notifications WHERE user_id = v_assigned_to AND related_id = p_task_id AND type = 'task_due';
    PERFORM public.create_notification(
      v_assigned_to,
      'Task Reminder',
      format('Reminder: Your assigned task "%s" is due soon.', v_task_name),
      'task_due',
      p_task_id
    );
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.send_task_due_reminder_notification()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  PERFORM public.send_task_due_reminder_for_task(id)
  FROM public.tasks
  WHERE status <> 'done' AND due_date IS NOT NULL AND due_date BETWEEN now() AND (now() + interval '1 day');
END;
$$;

-- AUTOMATIC CREATED_BY ASSIGNMENT
CREATE OR REPLACE FUNCTION public.set_created_by()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF NEW.created_by IS NULL THEN
    NEW.created_by := auth.uid();
  END IF;
  RETURN NEW;
END;
$$;

-- =========================================================================
-- 4. BIND TRIGGERS TO TABLES
-- =========================================================================
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
CREATE TRIGGER on_task_changes AFTER INSERT OR UPDATE ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.handle_task_changes();
CREATE TRIGGER on_board_member_changes AFTER INSERT ON public.board_members FOR EACH ROW EXECUTE FUNCTION public.notify_board_member_changes();
CREATE TRIGGER set_tasks_created_by BEFORE INSERT ON public.tasks FOR EACH ROW EXECUTE FUNCTION public.set_created_by();
CREATE TRIGGER set_boards_created_by BEFORE INSERT ON public.boards FOR EACH ROW EXECUTE FUNCTION public.set_created_by();
CREATE TRIGGER set_projects_created_by BEFORE INSERT ON public.projects FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

-- =========================================================================
-- 5. ROW LEVEL SECURITY (RLS POLICIES)
-- =========================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.boards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.board_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Profiles
CREATE POLICY profiles_read_all ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY profiles_self_write ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Projects
CREATE POLICY projects_owner_read ON public.projects FOR SELECT TO authenticated USING (created_by = auth.uid());
CREATE POLICY projects_owner_write ON public.projects FOR ALL TO authenticated USING (created_by = auth.uid()) WITH CHECK (created_by = auth.uid());

-- Boards
CREATE POLICY boards_read_all ON public.boards FOR SELECT TO authenticated USING (true);
CREATE POLICY boards_owner_write ON public.boards FOR ALL TO authenticated USING (created_by = auth.uid()) WITH CHECK (created_by = auth.uid());

-- Board Members
CREATE POLICY board_members_read ON public.board_members FOR SELECT TO authenticated USING (public.has_board_access(board_id) OR user_id = auth.uid());

CREATE POLICY board_members_insert ON public.board_members FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (SELECT 1 FROM public.boards b WHERE b.id = board_id AND b.created_by = auth.uid())
  OR public.get_board_role(board_id) IN ('Owner', 'Editor', 'Add/Delete Task')
  OR (user_id = auth.uid() AND status = 'Pending')
);

CREATE POLICY board_members_update ON public.board_members FOR UPDATE TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.boards b WHERE b.id = board_id AND b.created_by = auth.uid())
  OR public.get_board_role(board_id) IN ('Owner', 'Editor')
  OR user_id = auth.uid()
);

CREATE POLICY board_members_delete ON public.board_members FOR DELETE TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.boards b WHERE b.id = board_id AND b.created_by = auth.uid())
  OR public.get_board_role(board_id) = 'Owner'
  OR user_id = auth.uid()
);

-- Tasks
CREATE POLICY tasks_board_member_read ON public.tasks FOR SELECT TO authenticated USING (public.has_board_access(board_id));

CREATE POLICY tasks_board_member_update ON public.tasks FOR UPDATE TO authenticated
USING (
  public.get_board_role(board_id) IN ('Update Progress', 'Add/Delete Task', 'Editor')
  OR EXISTS (SELECT 1 FROM public.boards b WHERE b.id = board_id AND b.created_by = auth.uid())
);

CREATE POLICY tasks_board_member_insert ON public.tasks FOR INSERT TO authenticated
WITH CHECK (
  public.get_board_role(board_id) IN ('Add/Delete Task', 'Editor')
  OR EXISTS (SELECT 1 FROM public.boards b WHERE b.id = board_id AND b.created_by = auth.uid())
);

CREATE POLICY tasks_board_member_delete ON public.tasks FOR DELETE TO authenticated
USING (
  public.get_board_role(board_id) IN ('Add/Delete Task', 'Editor')
  OR EXISTS (SELECT 1 FROM public.boards b WHERE b.id = board_id AND b.created_by = auth.uid())
);

-- Notifications
CREATE POLICY notifications_self_read ON public.notifications FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY notifications_self_write ON public.notifications FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

-- =========================================================================
-- 6. INITIAL SYNC FOR EXISTING USERS
-- =========================================================================
INSERT INTO public.profiles (id, email, full_name)
SELECT id, email, COALESCE(raw_user_meta_data->>'full_name', raw_user_meta_data->>'name', split_part(email, '@', 1))
FROM auth.users ON CONFLICT (id) DO NOTHING;

-- =========================================================================
-- 7. ENABLE REALTIME STREAMING PUBLICATION CHANNEL
-- =========================================================================
ALTER TABLE public.notifications REPLICA IDENTITY FULL;
ALTER TABLE public.tasks REPLICA IDENTITY FULL;

DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.tasks;